---
parameters: []
provision:
  os: "rhel"
  stage: "base"
  provider: "aws"
sync_repos:
  - name: "origin"
actions:
  - type: "script"
    title: "use a ramdisk for etcd"
    script: |-
      sudo mkdir -p /tmp
      sudo mount -t tmpfs -o size=2048m tmpfs /tmp
      sudo restorecon -R /tmp
artifacts:
  - "/tmp/openshift"
generated_artifacts:
  installed_packages.log: 'sudo yum list installed'
  avc_denials.log: 'sudo ausearch -m avc'
  docker.info: 'sudo docker version && sudo docker info && sudo docker images && sudo docker ps -a'
system_journals:
  - docker.service