---
parent: 'common/test_cases/origin.yml'
extensions:
  actions:
    - type: "script"
      title: "build an origin release"
      repository: "origin"
      script: |-
        export OS_BUILD_IMAGE_ARGS=''
        hack/build-base-images.sh
        OS_ONLY_BUILD_PLATFORMS="linux/amd64" OS_BUILD_ENV_PRESERVE="_output/local" hack/env make release
