---
parent: 'test_cases/test_pull_request_openshift_ansible_extended_conformance_install.yml'
overrides:
  sync_repos:
    - name: "aos-cd-jobs"
    - name: "openshift-ansible"
      type: "pull_request"
    - name: "origin"
extensions:
  actions:
    - type: "host_script"
      title: "check other job statuses"
      script: |-
        /usr/bin/check-pull-request-status.py "${OPENSHIFT_ANSIBLE_PULL_ID}" /var/lib/jenkins/.config/hub