---
parent: 'test_cases/test_pull_request_openshift_ansible_extended_conformance_install.yml'
overrides:
  sync_repos:
    - name: "aos-cd-jobs"
    - name: "openshift-ansible"
      type: "pull_request"
    - name: "origin"
extensions:
  sync_repos:
    - name: "aos-cd-jobs"
  actions:
    - type: "host_script"
      title: "check other job statuses"
      repository: "aos-cd-jobs"
      script: |-
        git checkout sjb
        python check-pull-request-status.py "${OPENSHIFT_ANSIBLE_PULL_ID}" "${OPENSHIFT_ANSIBLE_TARGET_BRANCH}" /var/lib/jenkins/.config/hub test_status_config.yml